name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
permissions: write-all
jobs:
  build:
    name: Run Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          .\build.ps1
          # Pushing the sources and list to main
          git config --global user.email "palas@spworxx.com"
          git config --global user.name "Palasito"
          git add --all
          git commit -m "updating sources and list"
          git push
        shell: pwsh
