name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
permissions: write-all
jobs:
  build:
    name: Run Build
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: |
          & .\ip-country-data.exe
          # Pushing the sources and list to main
          git config --global user.email "chris.palavouzis@gmail.com"
          git config --global user.name "Palasito"
          git add --all
          git commit -m "updating sources and list"
          git push
        shell: pwsh
